version: 1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/hashamali/gcrypto
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
